export const DEFAULT_SLG_OFFERS = [
  {
    slug: "exhibition-partnership",
    name: "Exhibition Partnership",
    engineType: "revenue",
    offerType: "exhibition_partnership",
    summary: "Temporary or recurring exhibition partnerships for hospitality and private venues.",
    targetClusters: "boutique_hotel_hospitality,commercial_collectors_ecosystem,public_cultural_institutions",
    ticketMin: 2000,
    ticketMax: 12000,
    recurringPotential: 80,
    bundleable: true,
  },
  {
    slug: "urban-art-commission",
    name: "Urban Art Commission",
    engineType: "revenue",
    offerType: "urban_art_commission",
    summary: "Commissioned artworks, activations, and site-specific urban art projects.",
    targetClusters: "corporate_commission_buyers,boutique_hotel_hospitality,public_cultural_institutions",
    ticketMin: 5000,
    ticketMax: 40000,
    recurringPotential: 60,
    bundleable: true,
  },
  {
    slug: "curatorial-partnership",
    name: "Curatorial Partnership",
    engineType: "institutional",
    offerType: "curatorial_partnership",
    summary: "Curatorial, production, and program design partnership for institutions and cultural operators.",
    targetClusters: "public_cultural_institutions,festivals_placemaking,foundations_csr_philanthropy",
    ticketMin: 4000,
    ticketMax: 25000,
    recurringPotential: 75,
    bundleable: true,
  },
  {
    slug: "labirinto-residency-program",
    name: "LABirinto Residency Program",
    engineType: "institutional",
    offerType: "residency_program",
    summary: "Residency, production, and exchange format anchored in LABirinto.",
    targetClusters: "residency_exchange_diplomacy,foundations_csr_philanthropy,public_cultural_institutions",
    ticketMin: 6000,
    ticketMax: 30000,
    recurringPotential: 85,
    bundleable: true,
  },
  {
    slug: "festival-public-activation",
    name: "Festival / Public Space Activation",
    engineType: "authority",
    offerType: "festival_activation",
    summary: "Temporary public-program and placemaking activation rooted in urban art culture.",
    targetClusters: "festivals_placemaking,public_cultural_institutions,foundations_csr_philanthropy",
    ticketMin: 3000,
    ticketMax: 18000,
    recurringPotential: 70,
    bundleable: true,
  },
  {
    slug: "collector-corporate-advisory",
    name: "Collector / Corporate Advisory",
    engineType: "revenue",
    offerType: "collector_corporate_advisory",
    summary: "Art advisory, placement, and acquisition support for collectors and businesses.",
    targetClusters: "commercial_collectors_ecosystem,corporate_commission_buyers,boutique_hotel_hospitality",
    ticketMin: 1500,
    ticketMax: 10000,
    recurringPotential: 90,
    bundleable: true,
  },
  {
    slug: "educational-workshop-program",
    name: "Educational / Workshop Program",
    engineType: "institutional",
    offerType: "educational_program",
    summary: "Workshops, talks, and educational formats linked to urban art, territory, and social impact.",
    targetClusters: "schools_academies,public_cultural_institutions,foundations_csr_philanthropy",
    ticketMin: 800,
    ticketMax: 6000,
    recurringPotential: 65,
    bundleable: true,
  },
  {
    slug: "brand-culture-collaboration",
    name: "Brand x Culture Collaboration",
    engineType: "authority",
    offerType: "brand_culture_collaboration",
    summary: "Cultural collaboration packages for brands seeking authentic urban art positioning.",
    targetClusters: "corporate_commission_buyers,boutique_hotel_hospitality,international_urban_art_nodes",
    ticketMin: 4000,
    ticketMax: 25000,
    recurringPotential: 55,
    bundleable: true,
  },
] as const;

export const DEFAULT_SLG_NARRATIVES = [
  {
    slug: "urban-art-authority",
    name: "Urban Art Authority",
    summary: "Street Levels Gallery is a high-credibility urban art actor rooted in real scene knowledge and curatorial continuity.",
    toneOfApproach: "credible",
    engineTypes: "revenue,authority",
    targetClusters: "international_urban_art_nodes,commercial_collectors_ecosystem,boutique_hotel_hospitality",
  },
  {
    slug: "tuscany-uniqueness",
    name: "Tuscany Uniqueness",
    summary: "First and only urban art contemporary gallery in Tuscany, with a rare territorial position in Florence.",
    toneOfApproach: "differentiated",
    engineTypes: "revenue,authority",
    targetClusters: "boutique_hotel_hospitality,corporate_commission_buyers,international_urban_art_nodes",
  },
  {
    slug: "institutional-bridge",
    name: "Institutional + Independent Bridge",
    summary: "SLG connects independent artistic credibility with institutional programming and public legitimacy.",
    toneOfApproach: "institutional",
    engineTypes: "institutional,authority",
    targetClusters: "public_cultural_institutions,foundations_csr_philanthropy,festivals_placemaking",
  },
  {
    slug: "cultural-impact-social-value",
    name: "Cultural Impact + Social Value",
    summary: "The ecosystem combines cultural production with social and territorial impact through A Testa Alta and LABirinto.",
    toneOfApproach: "impact-led",
    engineTypes: "institutional",
    targetClusters: "foundations_csr_philanthropy,schools_academies,public_cultural_institutions",
  },
  {
    slug: "living-artist-ecosystem",
    name: "Living Artist Ecosystem",
    summary: "SLG activates a living ecosystem of artists, production, shows, and collaborations rather than one-off events.",
    toneOfApproach: "ecosystem",
    engineTypes: "revenue,institutional,authority",
    targetClusters: "commercial_collectors_ecosystem,public_cultural_institutions,boutique_hotel_hospitality",
  },
  {
    slug: "florence-strategic-node",
    name: "Florence Strategic Cultural Node",
    summary: "SLG operates inside Florence with rare adjacency to culture, tourism, institutions, and international visitors.",
    toneOfApproach: "strategic",
    engineTypes: "revenue,authority",
    targetClusters: "boutique_hotel_hospitality,corporate_commission_buyers,international_urban_art_nodes",
  },
  {
    slug: "labirinto-platform",
    name: "LABirinto Platform",
    summary: "LABirinto expands SLG from gallery into residency, production, and long-term cultural platform.",
    toneOfApproach: "programmatic",
    engineTypes: "institutional,authority",
    targetClusters: "residency_exchange_diplomacy,foundations_csr_philanthropy,public_cultural_institutions",
  },
] as const;

export const DEFAULT_SLG_CREDIBILITY_ASSETS = [
  {
    slug: "comune-firenze",
    name: "Comune di Firenze",
    assetType: "institutional_partner",
    summary: "Institutional relationship with the City of Florence.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "public_cultural_institutions,festivals_placemaking,foundations_csr_philanthropy",
    engineTypes: "institutional,authority",
    tags: "institutional,florence,public",
  },
  {
    slug: "fondazione-cr-firenze",
    name: "Fondazione CR Firenze",
    assetType: "foundation_partner",
    summary: "Relevant proof of trust for grant, co-funding, and cultural impact narratives.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "foundations_csr_philanthropy,public_cultural_institutions",
    engineTypes: "institutional",
    tags: "foundation,grant,cofunding",
  },
  {
    slug: "museo-novecento",
    name: "Museo Novecento",
    assetType: "museum_partner",
    summary: "Museum-level legitimacy for urban contemporary programming.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "public_cultural_institutions,international_urban_art_nodes",
    engineTypes: "authority,institutional",
    tags: "museum,curatorial,authority",
  },
  {
    slug: "four-seasons",
    name: "Four Seasons Firenze",
    assetType: "hospitality_partner",
    summary: "Premium hospitality proof for exhibition and art placement offers.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "boutique_hotel_hospitality,corporate_commission_buyers",
    engineTypes: "revenue,authority",
    tags: "hospitality,premium,florence",
  },
  {
    slug: "palazzo-castri",
    name: "Palazzo Castri",
    assetType: "hospitality_partner",
    summary: "Hospitality proof for exhibition and guest-program partnerships.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "boutique_hotel_hospitality",
    engineTypes: "revenue",
    tags: "hospitality,programming",
  },
  {
    slug: "street-art-museum-amsterdam",
    name: "Street Art Museum Amsterdam",
    assetType: "international_partner",
    summary: "International urban art ecosystem adjacency.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "international_urban_art_nodes,residency_exchange_diplomacy",
    engineTypes: "authority",
    tags: "international,urban-art,network",
  },
  {
    slug: "cheap-bologna",
    name: "CHEAP Bologna",
    assetType: "festival_partner",
    summary: "Strong urban intervention and public-program proof.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "festivals_placemaking,international_urban_art_nodes",
    engineTypes: "authority,institutional",
    tags: "festival,public-space,urban-art",
  },
  {
    slug: "artribune-press",
    name: "Artribune / Arts Press Coverage",
    assetType: "media_proof",
    summary: "Independent and specialized press validation across the ecosystem.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "commercial_collectors_ecosystem,boutique_hotel_hospitality,international_urban_art_nodes",
    engineTypes: "authority,revenue",
    tags: "press,authority,arts-media",
  },
  {
    slug: "labirinto-platform-proof",
    name: "LABirinto Platform",
    assetType: "programmatic_proof",
    summary: "Proof of long-term production, residency, and social-cultural platform building.",
    sourceUrl: "https://streetlevelsgallery.com",
    targetClusters: "residency_exchange_diplomacy,foundations_csr_philanthropy,schools_academies",
    engineTypes: "institutional,authority",
    tags: "labirinto,residency,impact",
  },
] as const;

export const DEFAULT_SLG_CASE_STUDIES = [
  {
    slug: "psa-festival",
    title: "PSA / Palazzuolo Strada Aperta",
    summary: "Recurring public-space activation proving SLG’s ability to orchestrate festival-grade programming in Florence.",
    targetCluster: "festivals_placemaking",
    engineType: "authority",
    artist: "Ache77",
    outcome: "Festival proof + public legitimacy + territorial narrative.",
    sourceUrl: "https://streetlevelsgallery.com",
    tags: "festival,public-space,florence",
  },
  {
    slug: "labirinto-launch",
    title: "LABirinto Launch and Platform Build",
    summary: "Expansion from gallery into residency and cultural platform model.",
    targetCluster: "residency_exchange_diplomacy",
    engineType: "institutional",
    artist: "Street Levels Gallery",
    outcome: "Platform proof + residency and co-production leverage.",
    sourceUrl: "https://streetlevelsgallery.com",
    tags: "labirinto,residency,production",
  },
  {
    slug: "double-space-florence",
    title: "Double-space Presence in Florence",
    summary: "Two-space setup strengthening continuity, curatorial density, and market confidence.",
    targetCluster: "commercial_collectors_ecosystem",
    engineType: "revenue",
    artist: "Street Levels Gallery",
    outcome: "Stronger commercial and curatorial positioning.",
    sourceUrl: "https://streetlevelsgallery.com",
    tags: "florence,gallery,continuity",
  },
  {
    slug: "hospitality-collaboration",
    title: "Hospitality Collaboration Track Record",
    summary: "Hospitality-facing proof for exhibition partnerships and art placement.",
    targetCluster: "boutique_hotel_hospitality",
    engineType: "revenue",
    artist: "Exit Enter",
    outcome: "Reduced perceived risk for hotel and premium hospitality partnerships.",
    sourceUrl: "https://streetlevelsgallery.com",
    tags: "hospitality,exhibition,placement",
  },
] as const;

export const DEFAULT_SLG_SEASONAL_WINDOWS = [
  {
    slug: "hospitality-q1-q3",
    name: "Hospitality Planning Window",
    engineType: "revenue",
    targetCluster: "boutique_hotel_hospitality",
    startMonth: 1,
    endMonth: 3,
    note: "Best for programming, rotations, and Q2/Q4 activation planning.",
  },
  {
    slug: "institutional-q1-q4",
    name: "Institutional Programming Window",
    engineType: "institutional",
    targetCluster: "public_cultural_institutions",
    startMonth: 1,
    endMonth: 4,
    note: "Best for annual program planning, co-production, and grant timing.",
  },
  {
    slug: "festival-spring-summer",
    name: "Festival and Public Activation Window",
    engineType: "authority",
    targetCluster: "festivals_placemaking",
    startMonth: 2,
    endMonth: 7,
    note: "Best for public-space and temporary activation cycles.",
  },
  {
    slug: "grants-foundations-q3-q4",
    name: "Grants and Foundation Window",
    engineType: "institutional",
    targetCluster: "foundations_csr_philanthropy",
    startMonth: 9,
    endMonth: 12,
    note: "Best for CSR, foundation, and co-funding conversations ahead of next-year programming.",
  },
  {
    slug: "fairs-collector-q3",
    name: "Fair and Collector Planning Window",
    engineType: "revenue",
    targetCluster: "commercial_collectors_ecosystem",
    startMonth: 9,
    endMonth: 11,
    note: "Best for collector-facing placements, fair-adjacent programming, and acquisition support.",
  },
  {
    slug: "schools-universities-q2-q3",
    name: "Schools and Universities Planning Window",
    engineType: "institutional",
    targetCluster: "schools_academies",
    startMonth: 5,
    endMonth: 9,
    note: "Best for academic-year workshops, talks, and educational program design.",
  },
] as const;

export const DEFAULT_SLG_CONTENT_ASSETS = [
  {
    slug: "hospitality-pitch-snippet",
    assetType: "pitch_snippet",
    engineType: "revenue",
    targetCluster: "boutique_hotel_hospitality",
    title: "Hospitality Pitch Snippet",
    body: "Street Levels Gallery can translate Florence-based urban contemporary culture into guest-facing exhibition, placement, and activation formats.",
  },
  {
    slug: "institutional-pitch-snippet",
    assetType: "pitch_snippet",
    engineType: "institutional",
    targetCluster: "public_cultural_institutions",
    title: "Institutional Pitch Snippet",
    body: "SLG combines independent curatorial credibility with institutional partnership experience and a programmatic platform through LABirinto.",
  },
  {
    slug: "authority-proof-snippet",
    assetType: "proof_snippet",
    engineType: "authority",
    targetCluster: "international_urban_art_nodes",
    title: "Authority Proof Snippet",
    body: "Street Levels Gallery operates as the first and only urban art contemporary gallery in Tuscany, with validated press, institutional, and international urban art adjacency.",
  },
  {
    slug: "hospitality-proof-snippet",
    assetType: "proof_snippet",
    engineType: "revenue",
    targetCluster: "boutique_hotel_hospitality",
    title: "Hospitality Proof Snippet",
    body: "SLG has already worked across hospitality-facing cultural formats in Florence, reducing perceived risk for curated guest experiences and art placement.",
  },
  {
    slug: "labirinto-program-snippet",
    assetType: "pitch_snippet",
    engineType: "institutional",
    targetCluster: "residency_exchange_diplomacy",
    title: "LABirinto Program Snippet",
    body: "LABirinto gives Street Levels Gallery a platform for residency, production, and exchange formats that go beyond exhibition-only collaboration.",
  },
  {
    slug: "revenue-cta-suggestion",
    assetType: "cta_suggestion",
    engineType: "revenue",
    targetCluster: null,
    title: "Revenue CTA",
    body: "Propose a 20-minute call to map one concrete pilot format, budget range, and first activation window.",
  },
  {
    slug: "institutional-cta-suggestion",
    assetType: "cta_suggestion",
    engineType: "institutional",
    targetCluster: null,
    title: "Institutional CTA",
    body: "Ask for the right program contact and propose a short concept note aligned with their next programming or funding window.",
  },
  {
    slug: "authority-cta-suggestion",
    assetType: "cta_suggestion",
    engineType: "authority",
    targetCluster: null,
    title: "Authority CTA",
    body: "Open relationship-first: share relevant proof, ask for a curatorial/network conversation, and avoid a hard sales pitch in the first touch.",
  },
] as const;
