import {
  pgTable,
  serial,
  text,
  numeric,
  integer,
  boolean,
  timestamp,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const businessesTable = pgTable(
  "businesses",
  {
    id: serial("id").primaryKey(),
    categorySlug: text("category_slug").notNull(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    latitude: numeric("latitude", { precision: 10, scale: 7 }).notNull(),
    longitude: numeric("longitude", { precision: 10, scale: 7 }).notNull(),
    addressLine: text("address_line"),
    city: text("city"),
    postalCode: text("postal_code"),
    region: text("region"),
    country: text("country"),
    website: text("website"),
    phone: text("phone"),
    osmId: text("osm_id"),
    osmType: text("osm_type"),
    googlePlaceId: text("google_place_id"),
    googleMapsUrl: text("google_maps_url"),
    rating: numeric("rating", { precision: 3, scale: 1 }),
    userRatingsTotal: integer("user_ratings_total"),
    hasWebsite: boolean("has_website").notNull().default(false),
    hasPhone: boolean("has_phone").notNull().default(false),
    enrichmentStatus: text("enrichment_status").notNull().default("pending"),
    discoveryStatus: text("discovery_status").notNull().default("discovered"),
    qualificationStatus: text("qualification_status").notNull().default("unqualified"),
    contactabilityStatus: text("contactability_status").notNull().default("unknown"),
    rankingStatus: text("ranking_status").notNull().default("pending"),
    sourceHealth: text("source_health"),
    contactReadiness: text("contact_readiness"),
    relevanceScore: integer("relevance_score"),
    contactabilityScore: integer("contactability_score"),
    confidenceScore: integer("confidence_score"),
    freshnessScore: integer("freshness_score"),
    priorityScore: integer("priority_score"),
    researchScore: integer("research_score"),
    engineType: text("engine_type"),
    targetType: text("target_type"),
    targetCluster: text("target_cluster"),
    economicValueScore: integer("economic_value_score"),
    strategicValueScore: integer("strategic_value_score"),
    referralValueScore: integer("referral_value_score"),
    prestigeValueScore: integer("prestige_value_score"),
    continuityRevenuePotential: integer("continuity_revenue_potential"),
    offerFitScore: integer("offer_fit_score"),
    relationshipPathScore: integer("relationship_path_score"),
    actionabilityScore: integer("actionability_score"),
    officialSourceCount: integer("official_source_count"),
    successfulSourceCount: integer("successful_source_count"),
    failedSourceCount: integer("failed_source_count"),
    primarySourceId: integer("primary_source_id"),
    primaryContactCandidateId: integer("primary_contact_candidate_id"),
    bestOfferId: integer("best_offer_id"),
    bestNarrativeId: integer("best_narrative_id"),
    secondaryNarrativeId: integer("secondary_narrative_id"),
    bestCredibilityAssetId: integer("best_credibility_asset_id"),
    bestCaseStudyId: integer("best_case_study_id"),
    proofAngle: text("proof_angle"),
    riskReductionReason: text("risk_reduction_reason"),
    toneOfApproach: text("tone_of_approach"),
    recommendedPitchAngle: text("recommended_pitch_angle"),
    nextBestContactWindow: text("next_best_contact_window"),
    accountTier: text("account_tier"),
    seasonalityFit: text("seasonality_fit"),
    readyForRelationship: boolean("ready_for_relationship").notNull().default(false),
    readyForInstitutionalPitch: boolean("ready_for_institutional_pitch").notNull().default(false),
    prestigeWatchlist: boolean("prestige_watchlist").notNull().default(false),
    cultivationRequired: boolean("cultivation_required").notNull().default(false),
    warmPathExists: boolean("warm_path_exists").notNull().default(false),
    readyForOutreach: boolean("ready_for_outreach").notNull().default(false),
    reviewRequired: boolean("review_required").notNull().default(false),
    reviewReason: text("review_reason"),
    topGap: text("top_gap"),
    recommendedNextStep: text("recommended_next_step"),
    outreachStatus: text("outreach_status").notNull().default("not_contacted"),
    contactName: text("contact_name"),
    contactRole: text("contact_role"),
    contactEmail: text("contact_email"),
    lastContactDate: date("last_contact_date", { mode: "string" }),
    nextActionDate: date("next_action_date", { mode: "string" }),
    assignedArtist: text("assigned_artist"),
    assignedArtistSource: text("assigned_artist_source"),
    avatarType: text("avatar_type"),
    targetMarket: text("target_market"),
    notes: text("notes"),
    warmConnection: text("warm_connection"),
    lastQualifiedAt: timestamp("last_qualified_at"),
    lastContactabilityCheckAt: timestamp("last_contactability_check_at"),
    lastResearchAt: timestamp("last_research_at"),
    nextResearchAt: timestamp("next_research_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    lastCheckedAt: timestamp("last_checked_at"),
  },
  (t) => [
    uniqueIndex("businesses_category_osm_idx").on(t.categorySlug, t.osmId, t.osmType),
    uniqueIndex("businesses_slug_category_idx").on(t.slug, t.categorySlug),
    index("businesses_city_idx").on(t.city),
    index("businesses_category_idx").on(t.categorySlug),
    index("businesses_has_website_idx").on(t.hasWebsite),
    index("businesses_outreach_status_idx").on(t.outreachStatus),
    index("businesses_next_action_idx").on(t.nextActionDate),
    index("businesses_assigned_artist_idx").on(t.assignedArtist),
    index("businesses_avatar_type_idx").on(t.avatarType),
    index("businesses_target_market_idx").on(t.targetMarket),
    index("businesses_ready_for_outreach_idx").on(t.readyForOutreach),
    index("businesses_ready_for_relationship_idx").on(t.readyForRelationship),
    index("businesses_ready_for_institutional_pitch_idx").on(t.readyForInstitutionalPitch),
    index("businesses_prestige_watchlist_idx").on(t.prestigeWatchlist),
    index("businesses_cultivation_required_idx").on(t.cultivationRequired),
    index("businesses_review_required_idx").on(t.reviewRequired),
    index("businesses_priority_score_idx").on(t.priorityScore),
    index("businesses_research_score_idx").on(t.researchScore),
    index("businesses_engine_type_idx").on(t.engineType),
    index("businesses_target_type_idx").on(t.targetType),
    index("businesses_target_cluster_idx").on(t.targetCluster),
    index("businesses_account_tier_idx").on(t.accountTier),
    index("businesses_warm_path_exists_idx").on(t.warmPathExists),
  ],
);

export const insertBusinessSchema = createInsertSchema(businessesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertBusiness = z.infer<typeof insertBusinessSchema>;
export type Business = typeof businessesTable.$inferSelect;
